//
//  Activity.swift
//  SpiritualGrowth1.0
//
//  Created by Brian Cordeau on 12/26/22.
//

import Foundation
import UIKit

var spiritualDisciplines = [Activity(title:"Pray", activity:"Pray for the last person you talked to", resource:"You may not know what they are going through, but the Lord sees it. Lift them in prayer to Him."),
                            Activity(title:"Pray", activity:"Pray for the person you last emailed", resource:"You may not know what they are going through, but the Lord sees it. Lift them in prayer to Him."),
                            Activity(title:"Journal", activity:"Spend an hour journaling about a topic that you have been thinking about", resource:"What is the first thing that comes to mind here? Something that pierces your mind each day when you first wake up is a good topic to start with. What fears do you have? What makes you anxious? Write about those things and give them to God. He can carry our burdens."),
                            Activity(title:"Study", activity:"Study a characteristic of God", resource:"The Bible Project has a great video series on this topic at https://bibleproject.com/explore/category/character-of-god-series/"),
                            Activity(title:"Bible Study", activity:"Read Psalm 119", resource:"Read online @ URL: https://www.biblegateway.com/passage/?search=Psalm%20119&version=NIV"),
                            Activity(title:"Give", activity:"Give to a cause you have been thinking about", resource:"Sometimes it is easy to get wrapped up in our day-to-day life and forget about those around us. Take some time today to look at organizations that help those who have less than you and give to them. The amount does not matter, the heart matters."),
                            Activity(title:"Pray", activity:"Spend 15 minutes listening to God", resource:"Set a timer for 15 minutes to just focus on listening to God. Remove all distractions from the room, make it completely dark if desired, and just listen."),
                            Activity(title:"Bible Study", activity:"Start a new devotional today", resource:"The Bible app has many great devotionals available to start today. Many are a week or fewer days that will help you stay in the habit of being in the Word daily and building a stronger relationship with the Lord. See them @ https://www.bible.com/reading-plans"),
                            Activity(title:"Listen", activity:"Find a Podcast to listen to on spiritual discipline", resource:"Use your favorite podcast app to search for keywords like Prayer, Fasting, Bible Study, etc. If you are not in the habit of listening to podcasts, give it a shot."),
                            Activity(title:"Fast", activity:"Fast from your 'go-to' website/app/show for three days", resource:"Block it from your browser if you need to, think about ways to use this time to grow closer to God, and spend that time in prayer, reading the Bible, meditating, or other activities."),
                            Activity(title:"Give", activity:"Sign up for a one-time volunteer event in your area", resource:"Pray about the needs in your community and just do it, try something, and see how it goes. Get your friends or family involved and make it a team sport. Do it now :)"),
                            Activity(title:"Pray", activity:"Take a walk around your neighborhood, praying for the people in each house as you go by", resource:"Pick some streets, a park, the square, or anywhere that people are and pray for them. Focus this time on lifting the community in prayer."),
                            Activity(title:"Listen", activity:"Play some hymns as you go about your day", resource:"Suggested Album, Chris Rice, Peace Like a River @ https://open.spotify.com/album/4FcJTO18RiqkZiWEMsXiAE"),
                            Activity(title:"Give", activity:"Secretly buy someone's lunch this week", resource:"https://www.biblegateway.com/passage/?search=Matthew+6%3A2&version=NIV"),
                            Activity(title:"Listen", activity:"Listen to a sermon on a topic you are interested in.", resource:"There are so many resources here, Voddie Baucham has a lot of great sermons @ https://www.voddiebaucham.org/sermons-listing/"),
                            Activity(title:"Fast", activity:"Do not use social media today", resource:"Not even LinkedIn :)."),
                            Activity(title:"Fast", activity:"Take your negative thoughts captive and pray against them", resource:"When you feel something negative come into your mind, pause, breathe, and pray about that specific thought."),
                            Activity(title:"Pray", activity:"Pray for a child in your life.", resource:"This is a good resource for parents @ https://www.amazon.com/Power-Praying%C2%AE-Parent-Stormie-Omartian/dp/0736957677, if you do not have children, think about nieces, nephews, or cousins and lift them in prayer today."),
                            Activity(title:"Community", activity:"Send your pastor a word of encouragement", resource:"Call, write a letter, text, email, social media, or however you feel like doing this. Think about things that your pastor does, characteristics, and anything encouraging, and reach out today."),
                            Activity(title:"Give", activity:"Send a gift to someone who is lonely", resource:"Think about those who are outside of your circle also, nursing homes, shelters, and foster children. You never know what impact you may make, it does not have to be something big."),
                            Activity(title:"Community", activity:"Do something kind for your neighbor", resource:"Cookies are always great! This is a great way to build community with those around you, simple acts of kindness matter."),
                            Activity(title:"Pray", activity:"Pray for the difficult coworker", resource:"Admit it, someone came to mind immediately. Pray for them, maybe they are going through difficult times, give them grace, and lift them."),
                            Activity(title:"Bible Study", activity:"Find a book to read on a topic you have been struggling with.", resource:"There are too many great books to think about here, ask your pastor for a good recommendation."),
                            Activity(title:"Pray", activity:"Pray with someone", resource:"People say all the time in church I'll pray for you, next time do it at that moment."),
                            Activity(title:"Community", activity:"Ask for forgiveness for a hurt you have caused, or forgive someone who has hurt you", resource:"Maybe you cannot do this in person, write a letter if you need to, and remember how God has forgiven you."),
                            Activity(title:"Community", activity:"Join a bible study with people of the same sex.", resource:"It is so important to have a group of men or women walking with you through life. Reach out and find them and engage the group do not give up after a couple of times, lean into this."),
                            Activity(title:"Community", activity:"Send a word of encouragement to someone who comes to mind today", resource:"Think about times this person has encouraged you, something unique about them, something they said or did, and use that as a time to reconnect."),
                            Activity(title:"Give", activity:"Take a shelter dog out for a walk", resource:"Animals need love also, find time to volunteer at the local animal shelter and walk and snuggle some dogs (or cats)."),
                            Activity(title:"Give", activity:"Volunteer to sort food at your local food bank", resource:"Many food banks across the nation need people to help sort, give out, or deliver food. Take some time to give back and feed the community, get out there, and serve."),
                            Activity(title:"Journal", activity:"Journal through the book of James this week", resource:"If you are not in the habit of journaling, try the S.O.A.P. method described @ https://onethingalone.com/the-soap-method-of-studying-the-bible/"),
                            Activity(title:"Give", activity:"Buy groceries for the person in line in front of you", resource:"Yes, it will be awkward, but if you can afford to do it, do it."),
                            Activity(title:"Pray", activity:"Go on a hike at a park, praying for the last three people you talked to", resource:"The solitude of parks is a great place to stop and pray in the quiet, to clear your mind and just focus on praying for these people."),
                            Activity(title:"Give", activity:"Sign up for a 5k that supports a cause you appreciate", resource:"You could walk, jog, run, roll, or do the 'sleep in' option. Wear that T-shirt proudly."),
                            Activity(title:"Give", activity:"Support a small business near you, and tip excessively if applicable", resource:"Shop local today, talk with the owners, artists, authors, and cooks, and ask questions. Get to know those in the community and how they got started."),
                            Activity(title:"Pray", activity:"Pray for the people of another country", resource:"Take a look @ https://operationworld.org/ and use this site, there are great suggestions on how to pray for each country. There is also a daily prayer calendar."),
                            Activity(title:"Community", activity:"Talk to a missionary about their passion for ministry", resource:""),
                            Activity(title:"Community", activity:"Tell your story to someone who has not heard it", resource:"Be authentic with those around you, your small group, church, and neighbors, when the opportunity arises. Pray for that opportunity."),
                            Activity(title:"Journal", activity:"Read through your journal from this time last year", resource:"If you are not in the habit of journaling, start today. You will be able to see the growth from year to year, very important to look back and see how God is guiding you forward."),
                            Activity(title:"Give", activity:"Make some bags of things for the homeless people you see as you are driving around.", resource:"Socks, underwear, food, water, make the bags and pray as you make them and hand them out. Change the day of one person."),
                            Activity(title:"Pray", activity:"Walk around your house praying for protection, peace, joy, love, growth, and kindness, so that it would be filled with the holy spirit.", resource:"Room to room, or walk around the full outside."),
                            Activity(title:"Fast", activity:"Leave the TV off today", resource:"Do not replace it with something else, just enjoy the silence."),
                            Activity(title:"Pray", activity:"Pray about how to take a recurring sin out by the roots", resource:"If you are not sure what it is, ask the Lord to shine a light in the dark areas."),
                            Activity(title:"Fast", activity:"Fast through two meals today praying about those who do not have enough to eat", resource:"If you are the one that does not have enough, pray for God's provision."),
                            Activity(title:"Community", activity:"Call a friend and praise a specific attribute that you admire about them.", resource:""),
                            Activity(title:"Study", activity:"Study baptism", resource:"This is a good starting point: https://www.biblegateway.com/topics/baptism"),
                            Activity(title:"Study", activity:"Commit a scripture verse to memory", resource:"There are some good memory verse apps on the app store, or just work through it each day until you have one committed to memory. Then try another."),
                            Activity(title:"Bible Study", activity:"Read 1 John", resource:"One chapter at a time each day is a good way to go, really letting it soak in, reading it, writing things down, read again at night. The word is a living fountain."),
                            Activity(title:"Study", activity:"Do a study on the word 'love'", resource:"This is a good starting point @ https://www.biblegateway.com/topics/love"),
                            Activity(title:"Journal", activity:"Write down three things you are thankful for and tell someone about them", resource:"Use your journal to write these things down, and talk with someone about them. Maybe they will come in handy in the future as well."),
                            Activity(title:"Music", activity:"Take some extra time to worship God", resource:"Set your alarm to get up earlier to spend some extra time just focusing on Him through worship music, prayer, and devotionals."),
                            Activity(title:"Community", activity:"Invite someone new from church to lunch.", resource:"This is a simple way to start building community."),
                            Activity(title:"Pray", activity:"Ask God to reveal Himself to you", resource:""),
                            Activity(title:"Music", activity:"Listen to only Christian music this week", resource:"Let this be a time to remember that what you put into your body and mind makes a difference. Sometimes it is easy to let the music seep in and not realize the impact it is having."),
                            Activity(title:"Bible Study", activity:"Pick a chapter in the Bible and read it several times throughout the day and ask God to speak to you through His Word. Focus on and pray about what stands out.", resource:"Look at the Psalms and Proverbs as a good starting point, many words of worship and wisdom in these two books."),
                            Activity(title:"Bible Study", activity:"Journal through chapter Psalm 19 today.", resource:"https://www.biblegateway.com/passage/?search=Psalm%2019&version=NIV"),
                            Activity(title:"Bible Study", activity:"Read through a passage in the Bible several times.", resource:"Pray as you read and ask God to speak through His Word. Focus on and pray about what stands out. Ask him to reveal related passages and seek them out."),
                            Activity(title:"Bible Study", activity:"If you are not in the habit of getting up first thing and praying and reading the Bible, try it.", resource:"Your mind has something kingdom-related to dwell on right away. Find a way to start your day with a focus on the Lord's will for your day."),
                            Activity(title:"Pray", activity:"As needs for others arise (myself too), ask for God's help and blessing.", resource:"Keep seeking the Lord throughout the day, and find ways to pause and refocus on Him. Thank Him for the parts of the day, even the hard parts."),
                            Activity(title:"Pray", activity:"Set an alarm to pray on the hour about whatever is on your mind.", resource:"Your phone alarm works well for this to set an hourly alarm to stop and pray."),
                            Activity(title:"Pray", activity:"Pray using the ACTS model.", resource:"Adoration - focus on attributes of God, who He is\nConfession - focus on confession of my sin and struggles, who I am.\nThanksgiving - Thank the Lord for something\nSupplication - asking for what I need\n"),
                            Activity(title:"Pray", activity:"Ask someone today how you can pray for them.", resource:"How can you be praying with/for them and listen for an opportunity to pray for those you can't ask. Make a list and commit to specific days/times that you can pray for people. Look for scripture that may apply. Follow up with those that you can."),
                            Activity(title:"Bible Study", activity:"Spend time weekly reading.", resource:"Get up a few minutes earlier each day to spend time in the word."),
                            Activity(title:"Pray", activity:"As you are walking or driving, dedicate this time to praying for others.", resource:"How much time do you spend in your car or transit each day? Shut off the music and spend time praying for people."),
                            Activity(title:"Pray", activity:"Listen to people today and take time to pray about their needs that have come up.", resource:""),
                            Activity(title:"Pray", activity:"Talk to God about anything.", resource:"Keep a constant conversation with the Lord today talking with Him as you are working, cleaning, doing whatever you are doing spend time in communication with Him."),
                            Activity(title:"Give", activity:"Pray for an opportunity to meet a need someone has.", resource:"Ask the Lord to show you the need you can meet today. It may not be financial, but maybe with a phone call or words of encouragement, you can make an impact on one person."),
                            Activity(title:"Worship ", activity:"Talk to God through music.", resource:"Music can be a powerful force in our life, think about the lyrics of the songs you listen to regularly and how they infiltrate your life."),
                            Activity(title:"Community", activity:"Celebrate with someone today in the name of the Lord.", resource:"Look back on your week and remember something that God has provided, find someone to celebrate that with. Lift His name, and remember that 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.' James 1:17, NIV. Celebrate these things and remember you were not the author of them, the Lord is."),
                            Activity(title:"Bible Study", activity:"Read the Word for 20 minutes today", resource:"Start the habit if you have not been reading the Word regularly, if you are already in the habit read another chapter. Read differently, out loud, with a different translation, and mix it up today."),
                            Activity(title:"Community", activity:"Talk and listen to other people about God.", resource:"The Lord works through community, it does not have to be a big study keep it simple and bring up the topic that you have been thinking about. Get others' thoughts on it and see."),
                            Activity(title:"Community", activity:"Do an act of service for someone today.", resource:"There are 125 listed @ https://parade.com/1308078/hollyhays/acts-of-service-love-language-ideas/, it does not have to be something major, little things matter here. This site is based on love languages, but most of these apply to anyone."),
                            Activity(title:"Pray", activity:"Ask God to forgive you of a sin you have been carrying around.", resource:""),
                            Activity(title:"Pray", activity:"Praise the Lord for something He has given you (talent, health, family, friends, etc)", resource:"Make a list of the things in your life that are blessings and remember where they came from. Find ways to be thankful even for those things that are hard to go through. What is God showing you through the hard things?"),
                            Activity(title:"Pray", activity:"Go to an area in the wilderness and be quiet with God", resource:"Find a place to be silent and focus on the Lord, bring something to write with, and just listen and write."),
                            Activity(title:"Community", activity:"Spend time praying for those who are currently locked up for their faith.", resource:"All across the world, some people are persecuted for their faith, spend time praying for them today. There is a resource @ https://www.persecution.com/globalprayerguide/ that can aid in how to pray for those who are being persecuted."),
                            Activity(title:"Community", activity:"Remember a time you got angry with someone recently? Forgive them if you have not and reach out to them.", resource:"But I tell you that anyone angry with a brother or sister will be subject to judgment. Again, anyone who says to a brother or sister, ‘Raca,’ is answerable to the court. And anyone who says, ‘You fool!’ will be in danger of the fire of hell.' Matthew 5:22 NIV\n\nit has been said that anger and unforgiveness are like a prison that we have built around ourselves take some time today to forgive the person. Ask God how best to do this."),
                            Activity(title:"Pray", activity:"Pray the Lord's prayer each hour on the hour today, and set an alarm if needed.", resource:".. ‘Our Father in heaven, hallowed be your name, your kingdom come, you will be done, on earth as it is in heaven. Give us today our daily bread. And forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from the evil one.’ Matthew 6:9-13"),
                            Activity(title:"Community", activity:"If you have something in your house that would bless someone else, take it to them today.", resource:"https://www.biblegateway.com/passage/?search=Matthew%206%3A19-21&version=NIV"),
                            Activity(title:"Reflect", activity:"Make a list of everything you watch, listen to, read, view on the internet, and reflect on this list. What are you letting enter your life that does not need to be there?", resource:"https://www.biblegateway.com/passage/?search=Matthew+6%3A22&version=NIV"),
                            Activity(title:"Reflect", activity:"Open your latest bank statement and think about what this says about the priorities of your life.", resource:"https://www.biblegateway.com/passage/?search=Matthew+6%3A24&version=NIV"),
                            Activity(title:"Reflect", activity:"What is something that is worrying you right now? Write it down and give it to the Lord in prayer.", resource:"Matthew 6:25"),
                            Activity(title:"Pray", activity:"Ask the Lord for a specific thing you have been wanting.", resource:"Matthew 7:7"),
                            Activity(title:"Pray", activity:"Seek the Lord only today. Throughout the day remind yourself to seek His guidance on how you spend resources.", resource:"Matthew 7:7"),
                            Activity(title:"Community", activity:"Knock on the door you have been afraid to knock on. Maybe it is a new job, relationship, friendship, or family member, today may be the time to build that bridge.", resource:"Matthew 7:7"),
                            Activity(title:"Reflect", activity:"Look at areas in your life where you look different from the community you live in. Where are you going through the narrow gate? If nothing comes to mind seek something like this out.", resource:"Matthew 7:13"),
                            Activity(title:"Reflect", activity:"Thinking back on this week, what were the fruits of the last week that you saw because of following the Lord?", resource:"Matthew 7:16-17"),
                            Activity(title:"Community", activity:"Reach out to your core group of friends and talk to them about what they are doing in their spiritual life to grow closer to the Lord.", resource:"We are meant to do life in community, talk to people about what they are doing to follow the Lord. This could also open some doors to setting up a regular time to discuss topics, progress, successes, failures and help to keep each other on track. It is important to have someone who is walking the same road as you.\n\nhttps://www.biblegateway.com/passage/?search=Matthew%207%3A24&version=NIV"),
                            Activity(title:"Reflect", activity:"What area of your life is holding you back from following the Lord 100%? Write this down and think about why this is stopping you.", resource:"Where does your security/hope/identity come from? Is it in your job, family, bank account or some other area that you can point to as your determination of success. These areas are not bad, but they are not the ultimate determination. By placing faith in what you can measure in terms of the world you are focusing on the wrong area of achievement. Look at these areas carefully and remember that God has given you these gifts, focus on the Giver more than the gifts.\n\nFor more on this subject get 'Counterfeit Gods'  by Tim Keller https://www.amazon.com/Counterfeit-Gods-Empty-Promises-Matters/dp/1594485496."),
                            Activity(title:"Listen", activity:"Find a sermon that deals with a topic that brings you anxiety and listen to this.", resource:"There are resources online that allow you to search for a specific topic. One of my favorite ones is Truth for Life which has a great catalog of Alistair Begg's sermons that you can search by topic, scripture, or series.\n\nhttps://www.truthforlife.org/resources/scripture/"),
                            Activity(title:"Listen", activity:"Listen to a podcast about a missionary who was punished for their beliefs.", resource:"Matthew 10:17"),
                            Activity(title:"Reflect", activity:"Write down the top priorities of your life right now and how those fit into building the kingdom of God.", resource:"Matthew 10:39"),
                            Activity(title:"Study", activity:"Read about the miracles Jesus performed throughout his ministry, let that soak in, and imagine yourself watching these things happen.", resource:"Matthew 11:21"),
                            Activity(title:"Reflect", activity:"Think about what the Sabbath looks like in your life, how are you honoring the Lord through rest?", resource:"In my personal life, it takes effort to rest, which sounds counterintuitive, but for me, I get to a place where I feel like I am moving too fast all of the time and I burn out. On Sundays I do not touch work or side projects that involve thinking about anything. For me yard work or cleaning the house is an activity that helps me disconnect. Hiking also does this in my life, rest does not have to be sitting around, what does this look like in your life?\n\nhttps://www.biblegateway.com/passage/?search=Matthew%2012%3A1-14&version=NIV"),
                            Activity(title:"Community", activity:"Make an effort today to increase your involvement in your church community, join a small group, sign up to volunteer, go to lunch with someone, and build the church.", resource:"The early church operated more like a family, sharing meals, being part of each other's lives, and walking together in all they did. Does your life look like this? It is easy to go to church and not make a connection to others on a Sunday morning. Make today the day you reach out, volunteer for something, join a small group, or invite someone out for lunch, you never know where it will lead.\n\nhttps://www.biblegateway.com/passage/?search=Matthew%2012%3A46-50&version=NIV"),
                            Activity(title:"Bible Study", activity:"Read 'The Parable of the Sower' in Matthew 13, and pray about how you can make the soil of your life more receptive to the word of God.", resource:"https://www.biblegateway.com/passage/?search=Matthew%2013&version=NIV"),
                            Activity(title:"Reflect", activity:"What weeds are in your life and how can you uproot them?", resource:"Weeds can destroy a garden of beautiful flowers quickly, a gardener has to be on guard to ensure this does not happen. Be on guard in your life and think about what you are letting into your mind that is choking out the beauty. It could be negative thoughts, past hurts, choice of entertainment, or any number of inputs. Take some time today when you feel the negativity creeping in to determine what the root cause was.\n\n https://www.biblegateway.com/passage/?search=Matthew%2013%3A36-39&version=NIV"),
                            Activity(title:"Reflect", activity:"What boat have you been clinging to in your life? Where has the Lord called you to step out in faith? Do it today.", resource:"Matthew 14:27-31"),
                            Activity(title:"Community", activity:"Pay close attention to the words you say today, especially at work and to your family or those closest to you. Are you honoring the Lord with your words?", resource:"The choice of words people use matters, for example when someone says 'I need a new.....' insert item here. There is a big difference between what I need and what I want. When wants become needs that is an area to examine because it could be that the thought is that that thing will bring joy. The ultimate joy comes from the Lord and serving Him, what does that look like in your life?\n\nhttps://www.biblegateway.com/passage/?search=Matthew%2015%3A10-11&version=NIV"),
                            Activity(title:"Community", activity:"If someone owes you a debt, pray about forgiving it today. If you have a debt, pray about how to get out of debt. It is a cage.", resource:"Matthew 18:21-35"),
                            Activity(title:"Fast", activity:"Think about what you spend most of your free time doing (social media, reading, TV, sports, etc), if it is not something for the Lord fast from that activity this week.", resource:"Matthew 19:21"),
                            Activity(title:"Reflect", activity:"God has given you many talents, list them out and how you are giving them back in service to the Lord.", resource:"Matthew 22:15-22"),
                            Activity(title:"Listen", activity:"Find a podcast to listen to about a person who has developed their God-given talents, how did they do it?", resource:"Matthew 25:22-23"),
                            Activity(title:"Study", activity:"Read some stories from Foxe's Book of Martyrs about people who did not back down in the face of death.", resource:"Matthew 26:31-32"),
                            Activity(title:"Go", activity:"Go and make disciples and be disciplined by someone.", resource:"Matthew 28: 16-20"),
                            Activity(title:"Pray", activity:"Praying for Emergency Personnel", resource:"Whenever you see or hear sirens, pray for emergency personnel. If it's an ambulance, pray for the patient and the EMTs. If it is a fire, pray for fire folks and whoever is involved in the potential situation. If it is the police or highway patrol, etc. pray for their safety and whoever they might interact with. You can also include life-flight or police helicopters when heard or seen."),
                            Activity(title:"Bible Study", activity:"Find a resource or app that works for you. The Youversion Bible app has many to choose from and is handy to have on your phone. There are topical or whole bible options.", resource:""),
                            Activity(title:"Pray", activity:"Pray John Wesley's Covenant Prayer throughout the day", resource:"John Wesley’s Covenant Prayer\n\n I am no longer my own, but yours.\nPut me to what you will, place me with whom you will.\nPut me to doing, put me to suffering.\nLet me be put to work for you or set aside for you,\nPraised for you or criticized for you.\nLet me be full, let me be empty.\nLet me have all things, let me have nothing.\nI freely and fully surrender all things\nTo your glory and service.\nAnd now, O wonderful and holy God,\nCreator, Redeemer, and Sustainer,\nYou are mine, and I am yours.\nSo be it.\nAnd the covenant which I have made on earth,\nLet it also be made in heaven.\nAmen.\n"),
                            Activity(title:"Go", activity:"Pause right now and think about an area God is asking you to trust in Him, take that step.", resource:"Proverbs 3:5-6"),
                            Activity(title:"Give", activity:"", resource:"Proverbs 3:9-10"),
                            Activity(title:"Reflect", activity:"Take time today to look at the direction you are headed in a particular area (relationships, career, parenting, etc) and ask the Lord for wisdom on the next steps.", resource:"Proverbs 5:26"),
                            Activity(title:"Journal", activity:"What area of your life have you been lazy and how can you correct this?", resource:"Proverbs 6:9-11"),
                            Activity(title:"Pray", activity:"Pray for the leaders in your life, pastor, boss, and political leaders that they would be led by the Lord in all they do.", resource:"Make a list and keep it somewhere that you will see it on a regular basis. You do not have to agree with everything they believe in or say and do, but ask the Lord how to pray for them. Leaders have high stakes decisions and need the wisdom of God to enable them to make good decisions.\n\nhttps://www.biblegateway.com/passage/?search=Proverbs%208%3A15-16&version=NIV"),
                            Activity(title:"Reflect", activity:"Ask the Lord to shine a light on any area that you have pride and remember to point back to the Lord in all things.", resource:"Proverbs 11:2")
]



struct Activity: Codable {
    var title: String
    var activity: String
    var resource: String
    var id = UUID()
    var count=0
    var activities=1
}




