//
//  Activity.swift
//  SpiritualGrowth1.0
//
//  Created by Brian Cordeau on 12/26/22.
//

import Foundation
import UIKit

var spiritualDisciplines = [Activity(title:"Pray",
                                     activity:"Pray for last person you talked to",
                                     resource:"You may not know what they are going through, but the Lord sees it. Lift them up in prayer to Him."),
                            Activity(title:"Pray", activity:"Pray for for the person you last emailed", resource:"You may not know what they are going through, but the Lord sees it. Lift them up in prayer to Him."),
                            Activity(title:"Journal", activity:"Spend an hour journaling about a topic that you have been thinking about", resource:"What is the first thing that comes to mind here? Something that pierces your mind each day when you first wake up is a good topic to start with. What fears do you have? What makes you anxious? Write about those things and give them to God. He can carry our burdens."),
                            Activity(title:"Study", activity:"Study a characteristic of Jesus", resource:""),
                            Activity(title:"Bible Study", activity:"Read Psalm 119", resource:""),
                            Activity(title:"Give", activity:"Give to a cause you have been thinking about", resource:"Sometimes it is easy to get wrapped up in our day to day life, and forget about those around us. Take some time today to look at organizations that help those who have less than you and give to them. The amount does not matter, the heart matters."),
                            Activity(title:"Pray", activity:"Spend 15 minutes listening to God", resource:"Set a timer for 15 minutes to just focus on listening to God. Remove all distractions from the room, make it completely dark if desired and just listen."),
                            Activity(title:"Bible Study", activity:"Start a new devotional today", resource:"The Bible app has many great devotionals available to start today. Many are a week or fewer days that will help you stay in the habit of being in the Word daily and building a stronger relationship with the Lord."),
                            Activity(title:"Listen", activity:"Find a Podcast to listen to on a spiritual discipline", resource:""),
                            Activity(title:"Fast", activity:"Fast from your 'go-to' website for three days", resource:""),
                            Activity(title:"Give", activity:"Sign up for a one time volunteer event in your area", resource:""),
                            Activity(title:"Pray", activity:"Take a walk around your neighborhood, praying for the people in each house as you go by", resource:""),
                            Activity(title:"Listen", activity:"Play some hymns as you go about your day", resource:""),
                            Activity(title:"Give", activity:"Secretly buy someone's lunch this week", resource:"Matthew 6:2"),
                            Activity(title:"Listen", activity:"Listen to a sermon on a topic you are interested in.", resource:""),
                            Activity(title:"Fast", activity:"Do not use social media today", resource:""),
                            Activity(title:"Fast", activity:"Take your negative thoughts captive and pray against them", resource:""),
                            Activity(title:"Pray", activity:"Pray for a child in your life.", resource:""),
                            Activity(title:"Community", activity:"Send your pastor a word of encouragement ", resource:""),
                            Activity(title:"Give", activity:"Send a gift to someone you know who is lonely", resource:""),
                            Activity(title:"Community", activity:"Do something kind for your neighbor", resource:""),
                            Activity(title:"Pray", activity:"Pray for the difficult coworker", resource:""),
                            Activity(title:"Bible Study", activity:"Find a book to read on a topic you have been struggling with, ask your pastor for a suggestion and go with it.", resource:""),
                            Activity(title:"Pray", activity:"Pray with someone today", resource:""),
                            Activity(title:"Community", activity:"Ask for forgiveness for a hurt you have caused, or forgive someone who has hurt you", resource:""),
                            Activity(title:"Community", activity:"Join a bible study with people of the same sex.", resource:""),
                            Activity(title:"Community", activity:"Send a word of encouragement to the person on your mind", resource:""),
                            Activity(title:"Give", activity:"Take a shelter dog out for a walk", resource:""),
                            Activity(title:"Give", activity:"Volunteer to sort food at your local food bank", resource:""),
                            Activity(title:"Journal", activity:"Journal through the book of James this week", resource:""),
                            Activity(title:"Give", activity:"Buy groceries for the person in line in front of you", resource:""),
                            Activity(title:"Pray", activity:"Go on a hike at a park, praying for the last three people you talked to", resource:""),
                            Activity(title:"Give", activity:"Sign up for a 5k that supports a cause you appreciate", resource:""),
                            Activity(title:"Give", activity:"Support a small business near you, tip excessively if applicable", resource:""),
                            Activity(title:"Pray", activity:"Pray for the people of another country", resource:""),
                            Activity(title:"Community", activity:"Talk to a missionary about their passion for ministry", resource:""),
                            Activity(title:"Community", activity:"Tell your story to someone who has not heard it", resource:""),
                            Activity(title:"Journal", activity:"Read through your journal from this time last year", resource:""),
                            Activity(title:"Give", activity:"Make some bags of things for the homeless people you see as you are driving around.", resource:""),
                            Activity(title:"Pray", activity:"Walk around your house praying for protection, peace, joy, love, growth, kindness, that it would be filled with the holy spirit.", resource:""),
                            Activity(title:"Fast", activity:"Leave the TV off today", resource:""),
                            Activity(title:"Pray", activity:"Pray about how to take a recurring sin out by the roots", resource:""),
                            Activity(title:"Fast", activity:"Fast through two meals today praying about those who do not have enough to eat", resource:""),
                            Activity(title:"Community", activity:"Call a friend and praise a specific attribute that you admire about them.", resource:""),
                            Activity(title:"Study", activity:"Study baptism", resource:""),
                            Activity(title:"Study", activity:"Commit a scripture verse to memory ", resource:""),
                            Activity(title:"Bible Study", activity:"Read 1 John", resource:""),
                            Activity(title:"Study", activity:"Do a study on the word 'love'", resource:""),
                            Activity(title:"Journal", activity:"Write down three things you are thankful for and tell someone about them", resource:""),
                            Activity(title:"Music", activity:"Take some extra time to worship God", resource:""),
                            Activity(title:"Community", activity:"Invite someone new from church to lunch.", resource:""),
                            Activity(title:"Pray", activity:"Ask God to reveal Himself to you", resource:""),
                            Activity(title:"Music", activity:"Listen to only Christian music this week", resource:""),
                            Activity(title:"Bible Study", activity:"Pick a chapter in the Bible and read it several times throughout the day ask God to speak to you through His Word. Focus on and pray about what stands out. ", resource:""),
                            Activity(title:"Bible Study", activity:"Journal through a chapter Psalm 19 today.", resource:""),
                            Activity(title:"Bible Study", activity:"Time spent reading a certain passage of the Bible. Usually several times through. I pray as I read and ask God to speak to me through His Word. Focus on and pray about what stands out . Sometimes regarding related passages. ", resource:""),
                            Activity(title:"Bible Study", activity:"This is an intentionally short and usually simple devotional time. My preference is to do it first thing in the morning so that my mind has something kingdom related to dwell on right away. / Separate from doing devotionals to fix my eyes on Jesus  early, I also just read. If I'm in a unique season I'll try and find a portion of the bible that parallels. If not I'll just pick a book of the bible ", resource:""),
                            Activity(title:"Pray", activity:"As needs for others arise (myself too), ask God's help and blessing.", resource:""),
                            Activity(title:"Pray", activity:"Set an alarm to pray on the hour about whatever is on your mind.", resource:""),
                            Activity(title:"Pray", activity:"Pray using ACTS model.", resource:"Adoration - focus on attributes of God, who He is\n Confession - focus on confession of my sin and struggles, who I am. \nThanksgiving - Thank the Lord for something\nSupplication - asking for what I need"),
                            Activity(title:"Pray", activity:"Ask someone today how you can pray for them. how I can be praying with/for them and listen for opportunity to pray for those I can't ask. I make a list and commit to specific days/times that I pray for everyone. I look for scripture that may apply. Last but not least I follow up on those that I can with each person.", resource:""),
                            Activity(title:"Bible Study", activity:"Spend time weekly reading.", resource:""),
                            Activity(title:"Fast", activity:"Focusing on God more than food or something else. ", resource:""),
                            Activity(title:"Pray", activity:"As you are walking or driving, dedicate this time to pray for others. ", resource:""),
                            Activity(title:"Pray", activity:"Listen to people today and take time to pray about their needs that have come up.", resource:""),
                            Activity(title:"Pray", activity:"Talk to god about anything ", resource:""),
                            Activity(title:"Give", activity:"Pray for an opportunity to meet a need someone has.", resource:""),
                            Activity(title:"Worship ", activity:"Talking to god through music ", resource:""),
                            Activity(title:"Community", activity:"Celebrate with someone today in the name of the Lord.", resource:""),
                            Activity(title:"Bible Study", activity:"Read the Word for 20 minutes today", resource:""),
                            Activity(title:"Community", activity:"Talk and listen to other people about god ", resource:""),
                            Activity(title:"Community", activity:"Do an act of service for someone today.", resource:""),
                            Activity(title:"Pray", activity:"Ask God to forgive you of a sin you have been carrying around. ", resource:""),
                            Activity(title:"Pray", activity:"Praise the Lord for something He has given you (talent, health, family, friends, etc)", resource:""),
                            Activity(title:"Pray", activity:"Go to an area in the wilderness and be quiet with God", resource:"Matthew 3:1"),
                            Activity(title:"Community", activity:"Spend time praying for those who are currently locked up for their faith.", resource:""),
                            Activity(title:"Community", activity:"Remember a time you got angry with someone recently. Forgive them if you have not and reach out to them.", resource:"Mathew 5:22"),
                            Activity(title:"Pray", activity:"Pray the Lord's prayer each hour on the hour today, set an alarm if needed.", resource:""),
                            Activity(title:"Community", activity:"You have something in your house that would bless someone else, take it to them today.", resource:"Matthew 6:19"),
                            Activity(title:"Reflect", activity:"Make a list of everything you watch, listen to, read, view on the internet and reflect on this list. What are you letting enter your life that does not need to be there?", resource:"Mathhew 6:22"),
                            Activity(title:"Reflect", activity:"Open your latest bank statement and think about what this says about the priorities of your life.", resource:"atthew 6: 24"),
                            Activity(title:"Reflect", activity:"What is something that is worrying you right now? Write it down and give it to the Lord in prayer.", resource:"Matthew 6:25"),
                            Activity(title:"Pray", activity:"Ask the Lord for a specific thing you have been wanting.", resource:"matthew 7:7"),
                            Activity(title:"Pray", activity:"Seek the Lord only today. Throughout the day remind yourself to seek His guidance on how you spend resources.", resource:"matthew 7:7"),
                            Activity(title:"Community", activity:"Knock on the door you have been afraid to knock on. Maybe it is a new job, relationship, friendship, family member, today may be the time to build that bridge.", resource:"matthew 7:7"),
                            Activity(title:"Reflect", activity:"Look at areas in your life where you look different from the community you live in. Where are you going through the narrow gate? If nothing comes to mind seek something like this out.", resource:"Matthew 7:13"),
                            Activity(title:"Reflect", activity:"Thinking back on this week, what were the fruits of the last week that you saw because of following the Lord?", resource:"Matthew 7:16-17"),
                            Activity(title:"Community", activity:"Reach out to your core group of friends and talk to them about what they are doing in their spiritual life to grow closer to the Lord.", resource:"Matthew 7:24"),
                            Activity(title:"Reflect", activity:"What area of your life is holding you back from following the Lord 100%? Write this down and think about why this is stopping you.", resource:"Matthew 8:19-22"),
                            Activity(title:"Listen", activity:"Find a sermon that deals with a topic that brings you anxiety and listen to this.", resource:"Matthew 8:26"),
                            Activity(title:"Listen", activity:"Listen to a podcast about a missionary who was punished for their beliefs.", resource:"Matthew 10:17"),
                            Activity(title:"Reflect", activity:"Write down the top priorities of your life right now and how those fit into building the kingdom of God.", resource:"Matthew 10:39"),
                            Activity(title:"Study", activity:"Read about the miracles Jesus performed throughout his ministry, let that soak in, imagine yourself watching these things happen.", resource:"Matthew 11:21"),
                            Activity(title:"Reflect", activity:"Think about what the Sabbath looks like in your life, how are your honoring the Lord through rest?", resource:"Matthew 12:1-14"),
                            Activity(title:"Community", activity:"Make an effort today to increase your involvement in your church community, join a small group, sign up to volunteer, go to lunch with someone, build the church.", resource:"Matthew 12:46-50"),
                            Activity(title:"Bible Study", activity:"Read 'The Parable of the Sower' in Matthew 13, pray about how you can make the soil of your life more receptive to the word of God.", resource:""),
                            Activity(title:"Reflect", activity:"What weeds are in your life and how can you uproot them?", resource:"Matthew13:36-39"),
                            Activity(title:"Reflect", activity:"What boat have you been clinging onto in your life? Where has the Lord called you to step out in faith? Do it today.", resource:"Matthew 14: 27-31"),
                            Activity(title:"Community", activity:"Pay close attention to the words you say today, especially at work and to your family or those closest to you. Are you honoring the Lord with your words?", resource:"Matthew 15:10-11"),
                            Activity(title:"Community", activity:"If someone owes you a debt, pray about forgiving it today. If you have a debt, pray about how to get out of debt. It is a cage.", resource:"Matthew 18:21-35"),
                            Activity(title:"Fast", activity:"Think about what you spend most of your free time doing (social media, reading, TV, sports etc), if it is not something for the Lord fast from that activity this week.", resource:"Matthew 19:21"),
                            Activity(title:"Reflect", activity:"God has given you many talents, list them out and how you are giving them back in service to the Lord.", resource:"Matthew 22:15-22"),
                            Activity(title:"Listen", activity:"Find a podcast to listen to about a person who has developed their God-given talents, how did they do it?", resource:"Matthew 25:22-23"),
                            Activity(title:"Study", activity:"Read some stories from Foxe's Book of Martyrs about people who did not back down in the face of death.", resource:"Matthew 26:31-32"),
                            Activity(title:"Go", activity:"Go and make disciples and be discipled by someone.", resource:"Matthew 28: 16-20"),
                            Activity(title:"Pray", activity:"Praying for Emergency Personnel", resource:"Whenever you see or hear sirens, pray for emergency personnel. If it's an ambulance, pray for the patient and the EMTs. If it is a fire, pray for fire folks and whoever is involved in the potential situation. If it is police or highway patrol, etc. pray for their safety and whoever they might interact with. You can also include lifeflight or police helicopters when heard or seen."),
                            Activity(title:"Bible Study", activity:"Find a resource or app that works for you. The Youversion Bible app has many to choose from and is handy to have on your phone. There are topical or whole bible options.", resource:""),
                            Activity(title:"Pray", activity:"Pray John Wesley's Covenant Prayer throughout the day", resource:"Various locations online, can be found in UM Hymnals, there are also pocket cards available for purchase in many places.John Wesley’s Covenant Prayer\nI am no longer my own, but yours.\n Put me to what you will, place me with whom you will.\nPut me to doing, put me to suffering.\nLet me be put to work for you or set aside for you,\n Praised for you or criticized for you.\nLet me be full, let me be empty.\nLet me have all things, let me have nothing.\nI freely and fully surrender all things\n To your glory and service.\n And now, O wonderful and holy God,\n Creator, Redeemer, and Sustainer,\nYou are mine, and I am yours.\n So be it.\nAnd the covenant which I have made on earth,\nLet it also be made in heaven.\nAmen."),
                            Activity(title:"Go", activity:"Pause right now and think about an area God is asking you to trust in Him, take that step.", resource:"Proverbs 3:5-6"),
                            Activity(title:"Reflect", activity:"Take time today to look at the direction you are headed in a particular area (relationships, career, parenting, etc) and ask the Lord for wisdom on the next steps.", resource:"Proverbs 5:26"),
                            Activity(title:"Journal", activity:"What area of your life have you been lazy and how can you correct this?", resource:"Proverbs 6:9-11"),
                            Activity(title:"Pray", activity:"Pray for the leaders in your life, pastor, boss, political leaders that they would be lead by the Lord in all they do.", resource:"Proverbs 8:15-16"),
                            Activity(title:"Reflect", activity:"Ask the Lord to shine a light on any area that you have pride and remember to point back to the Lord in all things.", resource:"Proverbs 11:2")
]



struct Activity: Codable {
    var title: String
    var activity: String
    var resource: String
    var id = UUID()
    var count=0
    var activities=1
}



